spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.main.allow-bean-definition-overriding=true
spring.flyway.locations=classpath:db/migration
# Replace with your actual database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/adventurebook
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.banner-mode=off
